#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: v1
kind: Namespace
metada:
  name: blue
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng
  namespace: blue
spec:
  selector:
    matchLabels:
      service: rng
  template:
    metadata:
      labels:
        service: rng
    spec:
      containers:
      -
        image: secobau/dockercoins-rng:release-1.1
        name: rng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hasher
  template:
    metadata:
      labels:
        service: hasher
    spec:
      containers:
      -
        image: secobau/dockercoins-hasher:release-1.1
        name: hasher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      -
        image: redis
        name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webui
  template:
    metadata:
      labels:
        service: webui
    spec:
      containers:
      -
        image: secobau/dockercoins-webui:release-1.1
        name: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker
  template:
    metadata:
      labels:
        service: worker
    spec:
      containers:
      -
        image: secobau/dockercoins-worker:release-1.1
        name: worker
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: blue
spec:
  ports:
  - port: 80
  selector:
    service: hasher
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: blue
spec:
  ports:
  - port: 6379
  selector:
    service: redis
---
apiVersion: v1
kind: Service
metadata:
  name: rng
  namespace: blue
spec:
  ports:
  - port: 80
  selector:
    service: rng
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: blue
spec:
  ports:
  -
    nodePort: 31001
    port: 80
  selector:
    service: webui
  type: NodePort
---
#########################################################################
